[package]
name = "phrase-upload-keys"
version = "0.1.0"
authors = ["David Pedersen <david.pdrsn@gmail.com>"]

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
reqwest = "0.9.4"
failure = "0.1.3"
clap = "~2.32"
pbr = "1.0.1"
